US1071443:  Define GET /entity-types/{id} API
folio-org/folio-query-tool-metadata pull request #4
Opened 2023-02-02 22:25 UTC by pkjacob

## Purpose
Define GET /entity-types/{id} API in folio-query-tool-metadata

## Approach
Add API definition to queryTool.yaml file

#### TODOS and Open Questions
None

## Learning
N/A

2023-02-15 14:04 UTC, TarasSpashchenko requested changes

2023-02-15 14:16 UTC, pkjacob commented on src/main/resources/swagger.api/queryTool.yaml
> +        - $ref: '#/components/parameters/x-okapi-tenant-header'
Thank You. I will update the PR

2023-02-15 16:54 UTC, pkjacob commented on src/main/resources/swagger.api/queryTool.yaml
> +        - $ref: '#/components/parameters/x-okapi-tenant-header'
@TarasSpashchenko  Done

2023-02-16 20:39 UTC, TarasSpashchenko approved these changes

2023-02-16 20:41 UTC, merged